### ISSUE TITLE
Fine-Grained SBIR Datasets (Chair-V2 & Shoe-V2) download link is broken

### ISSUE THREAD

**Issue by dahyun-kang** [AyanKumarBhunia/semisupervised-FGSBIR#1]
Hello,
I've recently come across this work in arxiv and really enjoyed it. Thank you for making the code publicly available so quickly! 😀

I have found that [the official download link](http://www.eecs.qmul.ac.uk/~qian/Project_cvpr16.html) for the Fine-Grained SBIR Datasets (Chair-V2 & Shoe-V2) in [your group's webpage](http://sketchx.eecs.qmul.ac.uk/downloads/) is currently not working:
![image](https://user-images.githubusercontent.com/32191670/115869865-753f1a80-a479-11eb-805f-b255547ea35c.png)
(The link is broken!)

Thank you so much in advance. 🙂

**Comment by AyanKumarBhunia** [comment]
https://drive.google.com/file/d/1frltfiEd9ymnODZFHYrbg741kfys1rq1/view?usp=sharing

See if it works.

**Comment by dahyun-kang** [comment]
> https://drive.google.com/file/d/1frltfiEd9ymnODZFHYrbg741kfys1rq1/view?usp=sharing
> 
> See if it works.

It works! (ChairV2 and ShoeV2 has 400 and 2000 images each.)
Thank you so much. :smile:

**Comment by ccq195** [comment]
Hi,  the number of sketch images is 6648/1275 from link https://drive.google.com/file/d/1frltfiEd9ymnODZFHYrbg741kfys1rq1/view?usp=sharing and https://drive.google.com/u/0/uc?id=15s2BR-QwLgX_DObQBrYlUlZqUU90EL9G&export=download, but in your paper is 6730/2000 of Shoev2 and Chairv2.  Did i put down the wrong dataset?  Looking forward to your reply . Thanks.
